### ISSUE TITLE
OpenOCD DAPLink Issue

### ISSUE THREAD

**Issue by Ashleyvk** [ARMmbed/DAPLink#844] opened 2021-08-17 10:36 UTC
I've downloaded the DAPLink firmware into the STM32WB55RG controller. In openocd, by selecting the interface as CMSIS-DAP, the following error is obtained.
 Error: The specified debug interface was not found (cmsis-dap)
@flit @asier70 @dotnfc @shiva-pandit

**Comment by elfmimi** [comment] 2021-08-21 00:01
Try openocd 0.11.0 .

**Comment by mathias-arm** [comment] 2021-10-06 04:50
I guess it's a duplicate of #792

**Closed by mathias-arm** 2021-10-06 04:50 UTC
