### ISSUE TITLE
USB / CDC / UART problem on win10 unsupported command

### ISSUE THREAD

**Issue by cederom** [ARMmbed/DAPLink#339] opened 2017-11-02 17:37 UTC
A problem was reported on win10 USB UART reports unsupported command, this needs to be investigated and fixed..

**Comment by cederom** [comment] 2017-11-03 00:04
As discussed with @c1728p9 who identified the issue this is an intermittent failure when multiple devices are tested on win10 host, error is reported by Python, needs more investigation..

**Comment by brianesquilona** [comment] 2018-12-28 22:42
Cannot reproduce this issue so will close it.

**Closed by brianesquilona** 2018-12-28 22:42 UTC
