### ISSUE TITLE
Mbed OS DAPLink Port

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/DAPLink#582] opened 2019-02-06 22:08 UTC
@flit Feasibility of porting DAPLink to Mbed OS?

- [x] build via mbed-cli

- [ ] Mbed OS RTOS API's? use RTX api's directly?

- [ ] Mbed OS peripheral API compatibility?

- [ ] Mbed OS USB Stack

- [ ] Tests?

**Comment by flit** [comment] 2019-02-14 17:30
Closing this as a duplicate of #197. The individual tasks are linked to that issue.

**Closed by flit** 2019-02-14 17:30 UTC
Labels: duplicate

**Comment by loverdeg-ep** [comment] 2019-02-14 19:35
@flit So the issues linked there are all that is needed to port daplink to mbed-os at this point?

**Comment by loverdeg** [comment] 2020-12-10 10:47
@flit Being that Im never satisfied with what actually exists or is remotely close to existing I wanted to capture a question about feasibility of eventually turning this project into an mbed OS library which would contain 'examples' for supported HIC's.

With more MCU's having secure swd support on the horizon it might be interesting to have the capability to integrate daplink into applications or bootloaders. In order to securely update other MCU's on the same PCB.
