### ISSUE TITLE
Flashing error with Drag and Drop due to Windows update

### ISSUE THREAD

**Issue by polat-ahmet** [ARMmbed/DAPLink#1032] opened 2023-06-21 07:25 UTC
While flashing the max32666fthr board with Drag and Drop using max32625 debugger, it often fails(nearly 70% fail, %30 success). It's ok when I try with small size(~40kb) binary, but I'm having trouble with bigger size(~500kb) binary. 

It was working properly before. I observed the problem using Windows updates [KB5026361](https://support.microsoft.com/en-us/topic/may-9-2023-kb5026361-os-builds-19042-2965-19044-2965-and-19045-2965-3edafffe-c3cc-4010-af43-2097c84c9437), [KB5025221](https://support.microsoft.com/en-us/topic/april-11-2023-kb5025221-os-builds-19042-2846-19044-2846-and-19045-2846-b00c3356-baac-4a41-8342-7f97ec83445a). When I uninstall these updates and tried it on [KB5023696](https://support.microsoft.com/en-us/topic/march-14-2023-kb5023696-os-builds-19042-2728-19044-2728-and-19045-2728-9a6dafce-d387-410d-a1bc-9ff5a9cafdc1), I did not encounter any problems, successfully flash. 

The fail message:
```
error: File sent out of order by PC. Target might not be programmed correctly.
type: transient
```

This is the [DETAILS.TXT](https://github.com/ARMmbed/DAPLink/files/11814393/DETAILS.TXT) of the DAPLink Firmware I used.

@mathias-arm It is a blocker issue for our release we will appreciate if you take a look and provide your feedback asap.

**Comment by mathias-arm** [comment] 2023-06-21 15:20
This sounds like a duplicate of #1025. Let's move the discussion there.

**Closed by mathias-arm** 2023-06-21 15:20 UTC
