### ISSUE TITLE
Compile only with ARMCC, not GCC ？😥

### ISSUE THREAD

**Issue by balanceTWK** [ARMmbed/DAPLink#672] opened 2019-11-18 02:54 UTC
[https://github.com/ARMmbed/DAPLink/issues/482](https://github.com/ARMmbed/DAPLink/issues/482)

**Comment by 0xc0170** [comment] 2019-11-19 08:13
Duplicate of #197 

That is known issue, we hopefully have GCC port soon. I'll close this one, keep track of #197

**Closed by 0xc0170** 2019-11-19 08:13 UTC
